name: Email Editor Package Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer vendor dependencies for MailPoet
        id: composer-mailpoet-cache
        uses: actions/cache@v4
        with:
          path: mailpoet/vendor
          key: ${{ runner.os }}-composer-mailpoet-${{ matrix.php-version }}-${{ hashFiles('mailpoet/composer.lock') }}-${{ hashFiles('mailpoet/composer.json') }}

      - name: Cache Composer vendor-prefixed dependencies for MailPoet
        id: vendor-prefixed-cache
        uses: actions/cache@v4
        with:
          path: mailpoet/vendor-prefixed
          key: ${{ runner.os }}-vendor-prefixed-${{ matrix.php-version }}-${{ hashFiles('mailpoet/prefixer/composer.lock') }}-${{ hashFiles('mailpoet/prefixer/composer.json') }}

      - name: Cache Composer vendor for test environment
        id: composer-tests-env-cache
        uses: actions/cache@v4
        with:
          path: tests_env/vendor
          key: ${{ runner.os }}-composer-mailpoet-${{ matrix.php-version }}-${{ hashFiles('tests_env/composer.lock') }}-${{ hashFiles('tests_env/composer.json') }}

      - name: Cache Composer dependencies for Email Editor
        id: composer-email-editor-cache
        uses: actions/cache@v4
        with:
          path: packages/php/email-editor/vendor
          key: ${{ runner.os }}-composer-email-editor-${{ matrix.php-version }}-${{ hashFiles('packages/php/email-editor/composer.lock') }}-${{ hashFiles('packages/php/email-editor/composer.json') }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd

      - name: Install tools
        run: |
          COMPOSER_DEV_MODE=1 php tools/install.php
          touch .env
        working-directory: mailpoet

      # Install Test Environment dependencies only if the cache was not hit
      - name: Install test environment dependencies
        if: steps.composer-tests-env-cache.outputs.cache-hit != 'true'
        run: ../mailpoet/tools/vendor/composer.phar install
        working-directory: tests_env

      # Install MailPoet dependencies only if the cache was not hit
      - name: Install mailpoet dependencies
        if: |
          steps.composer-mailpoet-cache.outputs.cache-hit != 'true' || steps.vendor-prefixed-cache.outputs.cache-hit != 'true'
        run: ./tools/vendor/composer.phar install
        working-directory: mailpoet

      # Install Email Editor dependencies only if the cache was not hit
      - name: Install email-editor dependencies
        if: steps.composer-email-editor-cache.outputs.cache-hit != 'true'
        run: ../../../mailpoet/tools/vendor/composer.phar install
        working-directory: packages/php/email-editor

      # Dump Email Editor autoload
      # This is needed to refresh classmap autoload when the composer cache is hit
      - name: Dump email-editor autoload
        run: ../../../mailpoet/tools/vendor/composer.phar dump-autoload
        working-directory: packages/php/email-editor

      # Dump MailPoet autoload
      # This is needed to refresh classmap autoload when the composer cache is hit
      - name: Dump MailPoet autoload
        run: ./tools/vendor/composer.phar dump-autoload
        working-directory: mailpoet

      # Run Email Editor unit tests
      - name: Run email-editor package unit tests
        run: ../../../tests_env/vendor/bin/codecept build && ../../../mailpoet/tools/vendor/composer.phar unit-test
        working-directory: packages/php/email-editor

      - name: Run email-editor package integration tests
        run: ../../../mailpoet/tools/vendor/composer.phar integration-test
        working-directory: packages/php/email-editor

  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install tools
        run: |
          COMPOSER_DEV_MODE=1 php tools/install.php
          touch .env
        working-directory: mailpoet

      - name: Install composer dependencies
        run: ../../tools/vendor/composer.phar install
        working-directory: mailpoet/tasks/code_sniffer

      - name: Run code style check
        run: ../../../mailpoet/tools/vendor/composer.phar code-style
        working-directory: packages/php/email-editor

  phpstan-static-analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer vendor dependencies for MailPoet
        id: composer-mailpoet-cache
        uses: actions/cache@v4
        with:
          path: mailpoet/vendor
          key: ${{ runner.os }}-composer-mailpoet-${{ matrix.php-version }}-${{ hashFiles('mailpoet/composer.lock') }}-${{ hashFiles('mailpoet/composer.json') }}

      - name: Cache Composer vendor-prefixed dependencies for MailPoet
        id: vendor-prefixed-cache
        uses: actions/cache@v4
        with:
          path: mailpoet/vendor-prefixed
          key: ${{ runner.os }}-vendor-prefixed-${{ matrix.php-version }}-${{ hashFiles('mailpoet/prefixer/composer.lock') }}-${{ hashFiles('mailpoet/prefixer/composer.json') }}

      - name: Cache Composer vendor for test environment
        id: composer-tests-env-cache
        uses: actions/cache@v4
        with:
          path: tests_env/vendor
          key: ${{ runner.os }}-composer-mailpoet-${{ matrix.php-version }}-${{ hashFiles('tests_env/composer.lock') }}-${{ hashFiles('tests_env/composer.json') }}

      - name: Cache Composer dependencies for Email Editor
        id: composer-email-editor-cache
        uses: actions/cache@v4
        with:
          path: packages/php/email-editor/vendor
          key: ${{ runner.os }}-composer-email-editor-${{ matrix.php-version }}-${{ hashFiles('packages/php/email-editor/composer.lock') }}-${{ hashFiles('packages/php/email-editor/composer.json') }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd

      - name: Install tools
        run: |
          COMPOSER_DEV_MODE=1 php tools/install.php
          touch .env
        working-directory: mailpoet

      # Install Test Environment dependencies only if the cache was not hit
      - name: Install test environment dependencies
        if: steps.composer-tests-env-cache.outputs.cache-hit != 'true'
        run: ../mailpoet/tools/vendor/composer.phar install
        working-directory: tests_env

      # Install MailPoet dependencies only if the cache was not hit
      - name: Install mailpoet dependencies
        if: |
          steps.composer-mailpoet-cache.outputs.cache-hit != 'true' || steps.vendor-prefixed-cache.outputs.cache-hit != 'true'
        run: ./tools/vendor/composer.phar install
        working-directory: mailpoet

      # Install Email Editor dependencies only if the cache was not hit
      - name: Install email-editor dependencies
        if: steps.composer-email-editor-cache.outputs.cache-hit != 'true'
        run: ../../../mailpoet/tools/vendor/composer.phar install
        working-directory: packages/php/email-editor

      - name: Install composer dependencies
        run: ../../tools/vendor/composer.phar install
        working-directory: mailpoet/tasks/phpstan

      # Dump Email Editor autoload
      # This is needed to refresh classmap autoload when the composer cache is hit
      - name: Dump email-editor autoload
        run: ../../../mailpoet/tools/vendor/composer.phar dump-autoload
        working-directory: packages/php/email-editor

      # Dump MailPoet autoload
      # This is needed to refresh classmap autoload when the composer cache is hit
      - name: Dump MailPoet autoload
        run: ./tools/vendor/composer.phar dump-autoload
        working-directory: mailpoet

      - name: Run code phpstan
        run: ../../../mailpoet/tools/vendor/composer.phar phpstan -- --php-version=${{ matrix.php-version == '7.4' && '70400' || '80200' }}
        working-directory: packages/php/email-editor
